### ISSUE TITLE
Error with React App in TypeScript

### ISSUE THREAD

**Issue by dave-moser** [aws/awsui-documentation#5] opened 2021-03-11 00:39 UTC
**Describe the bug**
When adding the awsui to a new typescript based React app, an error is thrown when accessing a page that contains an awsui component.

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

**To Reproduce**
1. create a new react app
npx create-react-app test-app --template typescript
cd test-app

2. install awsui packages
npm install @awsui/global-styles
npm install @awsui/components-react

3. add to the top of the index.tsx file
import "@awsui/global-styles/index.css"

4. add a button to the content in App.tsx
import Button from "@awsui/components-react/button"
<Button>Hello!</Button>

5. run the app
npm start

6. see the error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/54151448/110718214-64835f80-81bf-11eb-8760-1967d6825509.png)

**Environment (please complete the following information):**
 - OS: macOS
 - BrowserChrome

**Comment by dave-moser** [comment] 2021-03-11 01:09
if I downgrade the react app to 16.14.0 I do not get the errors.

package.json

    "@types/react": "^16.14.0",
    "@types/react-dom": "^16.9.9",
    "react": "^16.14.0",
    "react-dom": "^16.14.0"

**Comment by gethinwebster** [comment] 2021-03-11 08:25
Thanks for the report. We're looking into this - it's caused by a downstream dependency that still has a peer dependency on React 16. We hope to update this soon.

In the meantime, you can also work around this by installing `@awsui/components-react` using the `--legacy-peer-deps` command, so that it doesn't automatically install the peer dependency:

`npm install @awsui/components-react --legacy-peer-deps`

(note you need to uninstall the package first, if you're already installed it)

**Comment by gethinwebster** [comment] 2021-03-11 13:11
We have just released a new version of AWS UI to NPM with a fix for this: @awsui/components-react@3.0.73.

Enjoy using AWS UI Components with React 17!

**Closed by gethinwebster** 2021-03-11 13:11 UTC

**Comment by dave-moser** [comment] 2021-03-11 16:43
Works perfect!  Thanks for the quick fix!
